apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-rolebinding
  namespace: webapp
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: default
roleRef:
  kind: Role
  name: jenkins-admin-role
  apiGroup: rbac.authorization.k8s.io