apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-admin-role
  namespace: webapp
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]